config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  root 'users#index'
  resources :users
  resources :controllers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/controller.rb
class Controller < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/controllers_controller.rb
class ControllersController < ApplicationController
  before_action :set_controller, only: [:show, :edit, :update, :destroy]

  # GET /controllers
  # GET /controllers.json
  def index
    @controllers = Controller.all
  end

  # GET /controllers/1
  # GET /controllers/1.json
  def show
  end

  # GET /controllers/new
  def new
    @controller = Controller.new
  end

  # GET /controllers/1/edit
  def edit
  end

  # POST /controllers
  # POST /controllers.json
  def create
    @controller = Controller.new(controller_params)

    respond_to do |format|
      if @controller.save
        format.html { redirect_to @controller, notice: 'Controller was successfully created.' }
        format.json { render :show, status: :created, location: @controller }
      else
        format.html { render :new }
        format.json { render json: @controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /controllers/1
  # PATCH/PUT /controllers/1.json
  def update
    respond_to do |format|
      if @controller.update(controller_params)
        format.html { redirect_to @controller, notice: 'Controller was successfully updated.' }
        format.json { render :show, status: :ok, location: @controller }
      else
        format.html { render :edit }
        format.json { render json: @controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /controllers/1
  # DELETE /controllers/1.json
  def destroy
    @controller.destroy
    respond_to do |format|
      format.html { redirect_to controllers_url, notice: 'Controller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_controller
      @controller = Controller.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def controller_params
      params.require(:controller).permit(:post)
    end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
  end

  def goodbye
    @time = Time.now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/controllers/_form.html.erb
<%= form_with(model: controller, local: true) do |form| %>
  <% if controller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(controller.errors.count, "error") %> prohibited this controller from being saved:</h2>

      <ul>
        <% controller.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post %>
    <%= form.text_field :post %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/controllers/edit.html.erb
<h1>Editing Controller</h1>

<%= render 'form', controller: @controller %>

<%= link_to 'Show', @controller %> |
<%= link_to 'Back', controllers_path %>

app/views/controllers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Controllers</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @controllers.each do |controller| %>
      <tr>
        <td><%= controller.post %></td>
        <td><%= link_to 'Show', controller %></td>
        <td><%= link_to 'Edit', edit_controller_path(controller) %></td>
        <td><%= link_to 'Destroy', controller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Controller', new_controller_path %>

app/views/controllers/new.html.erb
<h1>New Controller</h1>

<%= render 'form', controller: @controller %>

<%= link_to 'Back', controllers_path %>

app/views/controllers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @controller.post %>
</p>

<%= link_to 'Edit', edit_controller_path(@controller) %> |
<%= link_to 'Back', controllers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectName</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye</h1>
<p>
Crurrent time: <%= @time %>
</p>

app/views/say/hello.html.erb
<h1>Hello world</h1>
<p>
Crurrent time: <%= @time %>
</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>